### ISSUE TITLE
Layout shift caused by discord username loading

### ISSUE THREAD

**Issue by LizAinslie** [LizAinslie/lizainslie.dev#4]
Julius suggested growing it like the star count grows on https://trpc.io/. Is a good idea, though I don't know how that fixes the CLS

**Comment by stoykotolev** [comment]
You better get to it then.

**Comment by LizAinslie** [comment]
*cries*

**Comment by stoykotolev** [comment]
Damn. Already has a PR as well.

**Comment by stoykotolev** [comment]
You still haven't looked over the PR though.
